# Generated by Django 5.0.14 on 2026-04-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='patronymic_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patronymic name'),
        ),
    ]
